
<script type="text/x-magento-init">
    {
     "#accordion": {
            "accordion": {
                "active": [],
                "collapsible": true,
                "openedState": "active",
                "multipleCollapsible": false
            }
        }
     }
</script>

<?php

/**
 * @var $block Ira\Author\Block\Author
 */
?>


<h1 id="widgets-header">Widgets</h1>

<div id="accordion">
    <div data-role="collapsible">
        <h5  data-role="title">Title</h5>
        <p data-role="content"></p>
    </div>
    <div data-role="collapsible">
        <h5  data-role="title">Title</h5>
        <p data-role="content"></p>
    </div>
    <div data-role="collapsible">
        <h5  data-role="title">Title</h5>
        <p data-role="content"></p>
    </div>
</div>