<script type="text/x-magento-init">
    {
        "#authors-header": {
            "Ira_Author/js/authors-header": {
                "newHeader": "Authors we have in our shop"
            }
        }
    }
</script>
<script type="text/x-magento-init">
    {
     "#accordion": {
            "accordion": {
                "active": [],
                "collapsible": true,
                "openedState": "active",
                "multipleCollapsible": false
            }
        }
     }
</script>

<?php

/**
 * @var $block Ira\Author\Block\Author
 */
?>


<h1 id="authors-header"></h1>

    <?php
        $id = $block->getParam();
        echo ' <div class="container__all" >';
        if (is_null($id)) {
            $authors = $block->getAuthors();
            foreach ($authors as $author) {
                echo '
            <div class="author_container">
                <div class="author_item">
                    <h5 class="author_name">  ' . $author->getName() . ' </h5>  
                    <a href=" ' . $block->getUrl('authors/index/index/id/' . $author->getId()) . '">
                        <img class="author_portrait" src=" ' . $block->getViewFileUrl($author->getImageUrls()) . ' ">         
                    </a> 
                            
                </div>
            </div>
            ';
            }
        } else {
            $author = $block->getAuthors();
            echo '
                <div class="author_container">
                    <h2 class="author_name">  ' . $author->getName() . ' </h2>
                    <img class="author_portrait" src=" ' . $block->getViewFileUrl($author->getImageUrls()) . ' ">
                    <p class="author_bio"> ' . $author->getBio() . ' </p>
                </div>';
        }
    echo ' </div>';?>



